name: Shell

on:
  push:
    branch:
      - main

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
